### ISSUE TITLE
AnimatedWeights 2.10 EFX Error

### ISSUE THREAD

**Issue by lunatico67** [mgfxer/ComfyUI-FrameFX#3]
When i load the AnimatedWeights 2.10 EFX workflow i get this error:
![Error2](https://github.com/user-attachments/assets/291514dc-652a-4646-907e-f51bb456059a)

**Comment by lunatico67** [comment]
![Error2](https://github.com/user-attachments/assets/a8b1977b-60e0-4730-ba83-71c2f75f2135)

**Comment by lunatico67** [comment]
![Error1](https://github.com/user-attachments/assets/252698c6-a951-478c-a87f-c235031ae5cf)

**Comment by mgfxer** [comment]
Another user had this error, and I'm having a hard time tracking it down. There is an alternate workflow in the workflows folder called tempfix. The only thing missing from the temp-fix workflow is the push retract functions. Give that a try for now, its 99% the same thing.

https://github.com/mgfxer/ComfyUI-FrameFX/tree/master/workflows

I will try to track down the issue but its hard to fix when you can't recreate the problem. It might be a conflict with some other node set. Usually if one node fails to load they all do, but in this case for certain users, just that node is not importing.

**Comment by mgfxer** [comment]
@lunatico67 pom on discord helped figure out the issue. I hadn't made the proper import in my init file. The repo has been updated. If you pull the latest version it should resolve the issue with that node.
